// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TY.LinkConverter.Context;

namespace TY.LinkConverter.Data.Migration
{
    [DbContext(typeof(DataContext))]
    [Migration("20210525203943_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TY.LinkConverter.Data.Entity.ToDeeplink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ParameterizedLink")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Pattern")
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ToDeeplinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 892, DateTimeKind.Utc).AddTicks(7132),
                            Deleted = false,
                            ParameterizedLink = "ty://?Page=Home",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 892, DateTimeKind.Utc).AddTicks(7663)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2672),
                            Deleted = false,
                            ParameterizedLink = "ty://?Page=Product&ContentId=[content]&CampaignId=[boutique]&MerchantId=[merchant]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\/(.*)\\/(.*)-p-(?<content>\\d+)\\?boutiqueId=(?<boutique>\\d+)&merchantId=(?<merchant>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2693)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2762),
                            Deleted = false,
                            ParameterizedLink = "ty://?Page=Product&ContentId=[content]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\/(.*)\\/(.*)-p-(?<content>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2763)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2782),
                            Deleted = false,
                            ParameterizedLink = "ty://?Page=Product&ContentId=[content]&CampaignId=[boutique]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\/(.*)\\/(.*)-p-(?<content>\\d+)\\?boutiqueId=(?<boutique>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2783)
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2801),
                            Deleted = false,
                            ParameterizedLink = "ty://?Page=Product&ContentId=[content]&MerchantId=[merchant]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\/(.*)/(.*)-p-(?<content>\\d+)\\?merchantId=(?<merchant>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2802)
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2829),
                            Deleted = false,
                            ParameterizedLink = "ty://?Page=Search&Query=[query]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\/sr\\?q=(?<query>.*$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(2830)
                        });
                });

            modelBuilder.Entity("TY.LinkConverter.Data.Entity.ToWebURL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ParameterizedLink")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Pattern")
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ToWebUrls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3367),
                            Deleted = false,
                            ParameterizedLink = "https://www.trendyol.com",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3370)
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3527),
                            Deleted = false,
                            ParameterizedLink = "https://www.trendyol.com/brand/name-p-[content]?boutiqueId=[campaign]&merchantId=[merchant]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\?Page=Product&ContentId=(?<content>\\d+)&CampaignId=(?<campaign>\\d+)&MerchantId=(?<merchant>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3528)
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3549),
                            Deleted = false,
                            ParameterizedLink = "https://www.trendyol.com/brand/name-p-[content]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\?Page=Product&ContentId=(?<content>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3550)
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3568),
                            Deleted = false,
                            ParameterizedLink = "https://www.trendyol.com/brand/name-p-[content]?boutiqueId=[campaign]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\?Page=Product&ContentId=(?<content>\\d+)&CampaignId=(?<campaign>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3569)
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3588),
                            Deleted = false,
                            ParameterizedLink = "https://www.trendyol.com/brand/name-p-[content]?merchantId=[merchant]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\?Page=Product&ContentId=(?<content>\\d+)&MerchantId=(?<merchant>\\d+$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3589)
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3609),
                            Deleted = false,
                            ParameterizedLink = "https://www.trendyol.com/sr?q=[query]",
                            Pattern = "^(\\w+)+?:\\/\\/(.*)\\?Page=Search&Query=(?<query>.*$)",
                            UpdateDate = new DateTime(2021, 5, 25, 20, 39, 42, 894, DateTimeKind.Utc).AddTicks(3610)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
